// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCx3MhOX0VIKaLDFdZViU-iRUTYXTb9Uo',
    appId: '1:32189873554:web:0d37b977273bf35c80d54b',
    messagingSenderId: '32189873554',
    projectId: 'hackatonuth',
    authDomain: 'hackatonuth.firebaseapp.com',
    storageBucket: 'hackatonuth.firebasestorage.app',
    measurementId: 'G-45XNM3SCHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5wOl8mLGZlUjSg_O9LraAuqb2wrIILFE',
    appId: '1:134255724924:android:13bbd8c49ed9e964c97cf9',
    messagingSenderId: '134255724924',
    projectId: 'consultoriouth-f6798',
    storageBucket: 'consultoriouth-f6798.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkJ10YaIhbggeH9pJN1JpWWEbYxLW9w14',
    appId: '1:32189873554:ios:27566bbb12456bef80d54b',
    messagingSenderId: '32189873554',
    projectId: 'hackatonuth',
    storageBucket: 'hackatonuth.firebasestorage.app',
    iosBundleId: 'com.example.consultorioequipo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkJ10YaIhbggeH9pJN1JpWWEbYxLW9w14',
    appId: '1:32189873554:ios:27566bbb12456bef80d54b',
    messagingSenderId: '32189873554',
    projectId: 'hackatonuth',
    storageBucket: 'hackatonuth.firebasestorage.app',
    iosBundleId: 'com.example.consultorioequipo1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCx3MhOX0VIKaLDFdZViU-iRUTYXTb9Uo',
    appId: '1:32189873554:web:f783a821a736e30080d54b',
    messagingSenderId: '32189873554',
    projectId: 'hackatonuth',
    authDomain: 'hackatonuth.firebaseapp.com',
    storageBucket: 'hackatonuth.firebasestorage.app',
    measurementId: 'G-43ZR3XQJLX',
  );
}